### ISSUE TITLE
Problem with analog inputs in 'direct' mode, when using community firmware

### ISSUE THREAD

**Issue by ftrobopy** [ftrobopy/ftrobopy#12]
I could not yet get the analog inputs (voltage, resistor) working in 'direct' mode, when running under the  community firmware. With the original ft firmware this works.

**Comment by ftrobopy** [comment]
The behavior is kind of random ...
I seems that ftrobopy in direct mode is missing some initialisation part. I still have to figure out what it is.

**Comment by ftrobopy** [comment]
bug in ftrobopy has been fixed

**Comment by rkunze** [comment]
@ftrobopy you can close issues directly from a commit - just add something along the lines of 'fixes #issue_number" to the commit message. This has the added benefit of linking to the commit from the issue and vice versa.

See also https://help.github.com/articles/closing-issues-via-commit-messages
