### ISSUE TITLE
Support for ROBO TX Controller

### ISSUE THREAD

**Issue by tutilo1** [ftrobopy/ftrobopy#13]
I have two fischertechnik ROBO TX Controller. Is ist possible to run ftrobopy with the TX Controller or only with the ROBOTICS TXT Controller? Is any support for the TX Controller planned or are there other possibilities to program the TX Controller with python?

Thanks for your help

**Comment by ftrobopy** [comment]
It is not possible to run ftrobopy with the ROBO TX Controller and currently I have no plans to write a ROBO TX port of the ftrobopy library.

I never had a ROBO TX controller myself, so I'm no expert on this but there is a pretty good (older) web page that gives an overview about ROBO TX programming languages at:
https://www.ftcommunity.de/ftComputingFinis/fishdllstx.htm

There seems to be a python module for the ROBO TX controller as well here:
https://www.ftcommunity.de/ftComputingFinis/zip/pythonfish311.zip
The pdf-manual can be found here:
https://www.ftcommunity.de/ftComputingFinis/pdf/FishFaTXPy311.pdf
