### ISSUE TITLE
Sound support in direct mode is unstable

### ISSUE THREAD

**Issue by harbaum** [ftrobopy/ftrobopy#16]
The sound support introduced with the direct mode is unstable. After playing a few random sounds for about half a minute no audio is generated anymore. The txtsndcat based programs then alyo don't work. But starting the original gui via launcher restores audio functionality.

E.e.g the following brickly program plays the "car horn" sound whenever the fire button is pressed:
  [Program](https://raw.githubusercontent.com/wiki/ftCommunity/ftcommunity-TXT/brickly_joystick.png)

After a few seconds constantly hitting the fire button audio stops working.

**Comment by harbaum** [comment]
This is related to https://github.com/ftCommunity/ftcommunity-TXT/issues/80

**Comment by ftrobopy** [comment]
I am not able to reproduce this problem. Could it be related to python3 (currently I cannot check with python3) or the spidev-module of the ftc-FW ?

Running ftrobopy version 1.71 with python 2.7, original-Firmware (4.2.4), self-compiled spidev-3.2, processes "run.sh" and "TxtControlMain" on TXT killed, in direct-mode.
The following code runs fine on the TXT:

import ftrobopy, random
txt=ftrobopy.ftrobopy('auto')
for i in range(100000):
  txt.play_sound(random.randint(20))

**Comment by harbaum** [comment]
I'll try to see if i can find the problem myself.

**Comment by harbaum** [comment]
Seems to be a local problem with my setup.

**Comment by ski7777** [comment]
I will try it later

**Comment by ski7777** [comment]
No problem here
