### ISSUE TITLE
start internal file

### ISSUE THREAD

**Issue by paoli7612** [ftrobopy/ftrobopy#23]
Hello,
How am i supposed to run a (".rpp") program written with robopro directly from it's module or the serial module? 
Thanks, appreciated the help, have a nice day

**Comment by ftrobopy** [comment]
ftrobopy is an open source python module that provides access to the fischertechnik TXTs I/Os in python only. It does not provide any support for robopro ".rpp" files which can only be run by using the original fischertechnik ROBOPro software. Currently there is no way to run a ".rpp" program from the linux command line of the TXT.

**Comment by paoli7612** [comment]
Thanks for your help, I really appreciated that
