### ISSUE TITLE
Opening Live View for Camera with TXT

### ISSUE THREAD

**Issue by MeqdadDev** [ftrobopy/ftrobopy#27]
Hi Dears,
I'm trying to open a **live view for the connected camera with TXT** using ftrobopy.

The possible thing that I've found is to take captures as screenshots from the cam.

So, first of all, is it possible with ftrobopy? and second, if possible; what commands should I start with?

Any help will be appreciated.

_Kind regards_

**Comment by ftrobopy** [comment]
Hi Meqdad,

"example/SimpleCameraDemo.py" shows, how to capture a single picture from the TXT camera. This will work in online-mode as well as in offline-mode. If you use the TXT community firmware (cfw), you have to start the FT-GUI app first in order for this to work.

In principle it is possible to grab each camera frame with this method to produce a video (or live stream).

To really show a live-camera picture on the display of the TXT (see e.g.  https://www.youtube.com/watch?v=Zgj_jSWz3dk ) some additional C-Code is neccessary, because Python itself is not fast enough to perform the decoding of the JPEG-picture that the camera delivers on the fly. If you are running the cfw you could use opencv for this task.

Kind regards,
Torsten

**Comment by MeqdadDev** [comment]
Hi Torsten,

Thanks for your explanation.

In my case, I didn't use community firmware for TXT, I'm using Client mode in TXT (i.e. its connected to my network router) with IP.
after checking the connection (like; ping command), I work in a code editor on my laptop to connect with TXT.

What I was asking about is to bring the live view of camera on my laptop screen. not the TXT screen.

**Comment by fh-kriftel** [comment]
Hello,

there is an example for showing (and interpreting) live video stream from TXT on the PC in this YouTube example, which uses ftrobopy (Thank you, for the great work, Torsten): https://youtu.be/VZqVndmCaeg it does show the code. 

Have fun!

**Comment by MeqdadDev** [comment]
Thanks @fh-kriftel 

I'll take a sneak peek on this example, it looks like the package is updated.
Thank you.

**Comment by christoschronopoulos** [comment]
As shown in the YouTube example video shared by @fh-kriftel, I am using the following code to get the image feed. It might be helpful to you @MeqdadDev . However, I always get errors after some seconds that interrupt the execution of my program. For example "Timeout while getting new frame from camera", "ERROR in camera thread:  [WinError 10054]" that lead to "Connection to TXT aborted" and freeze the feed windows (see image below). Any ideas, hints???

`#initialize ftrobopy interface
error = True
while error == True:
    #txt = ftrobopy.ftrobopy('192.168.7.2', 65000) # Connected by USB cable
    #txt = ftrobopy.ftrobopy('192.168.8.2', 65000) # Connected by WLAN AP
    #txt = ftrobopy.ftrobopy('192.168.1.242', 65000) # Connected by WLAN client
    txt = ftrobopy.ftrobopy('192.168.9.2', 65000) # Connected by Bluetooth
    print('Name of controller: ', txt.getDevicename())
    print('Version:', hex(txt.getVersionNumber()))
    time.sleep(2) #2
    try:
        txt.startCameraOnline()
        time.sleep(2.5) #2.5
        #im = "TXTframe.jpg"
        #frame resolution is 320x240 (W*H)
        pic = txt.getCameraFrame()
        if pic == None:
            error = True
        else:
            error = False
    except:
        print("Connection error")
        time.sleep(2)
        error = True

time.sleep(2.5)`

![image](https://user-images.githubusercontent.com/12989098/141784702-45a2fc51-3b97-49c9-9d8e-32f2598dafdc.png)

**Comment by fh-kriftel** [comment]
Suggest you get the new picture in a try / except way. 

Something like

error = True
while error = True:
try:
   pic = txt.getCameraFrame()
   error = False
except:
   pass

It can happen, that the camera does not send a frame successfully. 
Sometimes - when the TXT is idle for too long, it may not be able to connect with the camera at all. In this case, just restart the TXT.

**Comment by christoschronopoulos** [comment]
Thanks a lot @fh-kriftel !!! I will definitely try that and write back!!

**Comment by fh-kriftel** [comment]
Hi Christos,

l guess, it did not work. 
I have the similar or the same issue now.

I detect and read a marker from the txt camera stream successfully and show the enrichment image with CV.imshow without problem.

However, I wanted to show a plot of the marker location in the same loop with matplotlib. This fails in the way you describe it. 
The code works perfectly with the laptop cam. 

Maybe Torsten has an idea, what may potentially break it.  
Possibly there is a max idle time between reading 2 frames. 
I will try to read the camera frames in a thread and share results.

**Comment by ftrobopy** [comment]
Hi fh-kriftel,

ftroboby already starts its own camera-thread to read the camera data from the TXT, so there should be no need to start an additional thread. However there may be a problem in the ftrobopy camera thread itself. It could be a timing problem or a race condition (maybe related to faster modern computers ?). I will have a closer look at this part of the code again.

**Comment by fh-kriftel** [comment]
My bad. Everything fine with your code, but not with mine. 
In some part of copied code I used a variable with the name 'txt' for a text. 
However, txt was prior bound to the ftrobopy class...
Definitely such a mistake causes the error mentioned above - loss of camera frame, as the whole TXT gets disconnected...
