### ISSUE TITLE
Reading C1-C4 from RoboTXT Controller

### ISSUE THREAD

**Issue by ronsei** [ftrobopy/ftrobopy#28]
We have several of the RoboTXT controllers from Fischertechnik in use with the Training Factory 4.0 and we are using ftrobopy to control the individual components of the production stations connected to the controllers. There are also some switches connected to the ports C1 to C4. Is there support by ftrobopy to read the values of the input devices connected to these ports? If so, how does this work?

**Comment by ftrobopy** [comment]
Yes, you can read the fast counters C1-C4 directly with ftrobopy. There are two functions that relate to this task:

1. getCurrentCounterInput(idx) returns 1 or 0 if the value of the indexed (idx+1) C1-C4 input has changed (ret 1) or not changed (ret 0)
2. getCurrentCounterValue(idx) returns the current value of the indexed C1-C4 input.

This will work even without setting up a motor object beforehand. However if there exists a motor object, the value of getCurrentCounterValue(idx) will be reset to 0 each time the motor.setDistance() function is called.

**Comment by ronsei** [comment]
Works like a charm. Thanks a lot for the fast response!
