### ISSUE TITLE
getCurrentInput returns always 1

### ISSUE THREAD

**Issue by itcrabmeat** [ftrobopy/ftrobopy#29]
Hey,
if a button is pressed at the time of connection (ftrobopy.ftrobopy('auto',use_extension=True) when the extension is used, the method getCurrentInput will always return 1.
If the button input isn't pressed at the time of connection everything will run fine.

**Comment by ftrobopy** [comment]
Yes, this is a bug in ftrobopy that I recently became aware of. It happens when using 2 TXTs in master-slave mode. I am currently analysing this error and hope to have a fix soon.

**Comment by ftrobopy** [comment]
The Issue has been resolved in Version 1.97 of ftrobopy
