### ISSUE TITLE
Vacuum Gripper Robot support

### ISSUE THREAD

**Issue by christoschronopoulos** [ftrobopy/ftrobopy#30]
Thank you for the great work! I would like to ask whether the VGR is supported by the ftrobopy so I can program it in Python. Any insight?

**Comment by ftrobopy** [comment]
Yes, it is possible to program the fischertechnik Vaccum Gripper Robot for TXT in Python with ftrobopy.
(the pneumatic valves are connected to a standard output of the TXT and can thus be controlled by ftrobopy)

**Comment by christoschronopoulos** [comment]
That's great! Thanks for the response!

**Comment by fh-kriftel** [comment]
What is your exact doubt or question? Having used ftrobopy a lot, I would not see a constraint.

**Comment by christoschronopoulos** [comment]
@fh-kriftel the doubt was about whether I could I actuate the pneumatic valves programmatically.

**Comment by fh-kriftel** [comment]
Not a problem. Similar to a lamp. Just assign full power (512) or off (0) to the related output.
