### ISSUE TITLE
Error in SyncDataBegin und SyncDataEnd

### ISSUE THREAD

**Issue by IJMTutorSES** [ftrobopy/ftrobopy#31]
i think it should be:
```python
if self._use_TransferAreaMode
```
and not:
```python
if self._use_TransferArea
```

**Comment by ftrobopy** [comment]
This bug has already been corrected in Version 1.98
But thanks for the hint! (I think I missed pushing Version 1.98, sorry for that)

**Comment by ftrobopy** [comment]
1.98 has been pushed
