### ISSUE TITLE
setup.py installs old version

### ISSUE THREAD

**Issue by hypnotoad** [ftrobopy/ftrobopy#35]
Not too important, but confusing. `setup.py` does not install the current git version but an old one from github.

**Comment by hypnotoad** [comment]
This also affects "pip install" which installs an old 1.8.

**Comment by ftrobopy** [comment]
setup.py has been updated and version 2.0.0 of ftrobopy has been published on pypi.org.
    pip install ftrobopy
should install version 2.0.0 now
