### ISSUE TITLE
Error in documentation for voltage() method

### ISSUE THREAD

**Issue by otfried** [ftrobopy/ftrobopy#9]
The documentation says that the object begin returned has a method `value()`.  But in the code it is called `voltage()`.

**Comment by otfried** [comment]
Also:  The method `resistor()` returns an object that supports the method `value()`.   For consistency, this should be called `resistance()` (or both could be allowed).

Note that the object returned by `resistor2()` already uses the `resistance()` method.  However, the method doesn't work, since it uses `C_RESISTANCE2` instead of `C_RESISTOR2`.  But even after changing this I could not get this to work - it always returns 0, both for the FT NTC-resistor and the FT light transistor.

**Comment by otfried** [comment]
I looked in the FT Documentation to find out what the difference between C_RESISTOR and C_RESISTOR2 is.   I suggest to rename the two methods:

```
resistor()  --> resistor5k()
resistor2() --> resistor15k()
```

The documentation should state that the first returns an Ohm value between 10 and 4999, with 5000  meaning a resistance out of range,  while the second returns an Ohm value between 30 and 14999, with 15000 meaning out of range.

**Comment by otfried** [comment]
My problem with using the `resistor2` method may simply be that TXT firmware is too old.  I will test again after updating.   But the use of `C_RESISTANCE2` instead of `C_RESISTOR2` is a real bug.

**Comment by ftrobopy** [comment]
Thank you for your hints. The bug has been corrected.
I agree to the renaming of resistor --> resistor5k and resistor2 --> resistor15k which is more precise.
I could not yet test, if resistor15k really works. So I leave this issue open until resistor15k has been positively tested.

**Comment by otfried** [comment]
Vielleicht waere es noch schoener, die zwei Methoden zu vereinigen, und den Messbereich ueber einen Parameter festzulegen.  (Die zwei Methoden unterscheiden sich nur in einer einzigen Konstanten).  Hier ist ein patch:

[patch.txt](https://github.com/ftrobopy/ftrobopy/files/540095/patch.txt)

Der Patch korrigiert ausserdem die Dokumentation von `voltage` von "Volt" auf "Millivolt".  Alternativ koennte man natuerlich den Rueckgabewert durch 1000 teilen.

**Comment by ftrobopy** [comment]
I tried to map the RoboPro objects to Python as closely as possible. Since resistor and resistor2 are 2 different objects in RoboPro I made them to be different objects in python, too. However, what you propose makes sense and will apply your patch.
Could you positively test the resistor15k function ?

**Comment by otfried** [comment]
Unfortunately I don't have a stable power supply now.  I'm currently running my TXT from a 9V block battery, and I don't dare doing the firmware update with this...   My current firmware is 4.1.5, and it actually returns 15000 when using the `resistor()` method.  It returns 0 when using the `resistor2()` method.

I will do some real tests with real resistors when I have updated the firmware back at home.

I didn't realize the correspondence with RoboPro objects since I haven't used it yet  :-)   I got my TXT only yesterday...

**Comment by otfried** [comment]
I upgraded the Firmware on my TXT to the newest one.  It seems the FT documentation I mentioned before is wrong or no longer correct.

So here are what seem to be correct improvements to the documentation:

* Throughout `ftrobopy.py`, change `Wiederstand` to `Widerstand`
* In the documentation of the `voltage()` method, change `Volt` to `milliVolt` (3 times).
* In the documentation of the `resistor()` method, change ` Der am Eingang anliegende Wiederstandswert` to ` Der am Eingang anliegende Widerstandswert in Ohm fuer Widerstaende bis 15kOhm, fuer hoehere Widerstandswerte wird immer 15000 zurueckgegeben`

And I have no idea what the `resistor2` method is supposed to do - it always returns zero.   Maybe it should be deleted from ftrobopy.

**Comment by ftrobopy** [comment]
I implemented the changes you proposed and I had a close look at what the resistor2()-function really is doing internally (I only implemented it in the first place due to compatibility reasons to ROBOPro):
The motor shield of the TXT interprets the resistor2()-function in the exact same way as the voltage()-function, e.g. it measures a voltage between 5mV and 10V. It does not measure a resistance despite its name. For me it is currently unclear why this function exists in ROBOPro. Still, I will leave it in but I changed the documentation for it accordingly.
It also happens, that the function trailfollower() is internally also treated like voltage(). In ROBOPro trailfollower() has a digital result though. I adapted this in ftrobopy and changed the manual accordingly.

**Comment by otfried** [comment]
May I ask how you verified what happens on the motor shield?  Is there some documentation available?  Or are you snooping on what goes over the serial link to the shield?

**Comment by ftrobopy** [comment]
Besides snooping and guessing, I had access to some additional information (which is meanwhile non-disclosed). That's how I could implement the "direct"-Mode into ftrobopy, which is used in the newest community-FW to directly access the motor shield over the internal serial port of the TXT.

**Comment by otfried** [comment]
Could it be that the "C_RESISTOR2" value existed in an earlier version of RoboPro and was removed?

In the current version of the RoboPro software I could not find any way to select this mode in the properties of any of the input tests.   And certainly the documentation in `FtShmem.h` seems no longer correct, as in mode 1 (MODE_R) the range is now up to 15kOhm.   The header says this was for firmware 1.30...

**Comment by ftrobopy** [comment]
It is true that the resistor2() input function does not exist in RoboPro (any more ?). It could be an old relic from the times of the fischertechnik Robotics-Interface (?). When I initially got the value from the file FtShmem.h it didn't occur to me, that it was not used any more.

I completely removed it from ftrobopy.
